baseURL = "https://jordiburgos.com/"
languageCode = "en-us"
title = "Jordi Burgos"

theme = "hyde-hyde"

[permalinks]
  posts = "/posts/:year/:slug/"

highlightjs = true
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

# hyde config

[Menus]
  main = [
      {Name = "Posts", URL = "/posts/", weight = 1},
      {Name = "Github", URL = "https://github.com/jmaister"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/jordiburgos/"},
      {Name = "Twitter", URL = "https://twitter.com/jordimaister"}
  ]

[params]
  #date_format = "2006-Jan-02"

  description = "Personal blog"

  themeColor = "theme-base-08"

googleAnalytics = "UA-45872762-1"
