## Basic Configuration
baseurl = "https://jordiburgos.com/"
languageCode = "en"

title = "Jordi Burgos"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
googleAnalytics = "UA-45872762-1"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

# Make URLs look like /post/yyyy/name.html instead of /post/yyyy/name/
uglyurls = true

[permalinks]
  posts = "/post/:year/:slug/"

## Site Settings
[params]
    author = "Jordi Burgos"
    title = "Personal blog"
    description = "I am a Software Engineer. Here are some notes to keep track of what I do and some experiments."
    authorimage = "images/gravatar300.jpeg"
    dateformat = "2 Jan 2006"

    # sidebar, copyright & license
    copyright = "Jordi Burgos"
    since = 2013
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "monokai"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

    themeColor = "theme-base-08"

## Social Accounts
[params.social]
    github = "jmaister"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "jordiburgos"
    twitter = "jordimaister"
    #facebook = "<username>"
    stackoverflow = "1108098/jordiburgos"
    #telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    email = "jordiburgos@gmail.com"
    #gravatar = "jordiburgos@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
#[[menu.main]]
#    name = "Portfolio"
#    identifier = "portfolio"
#    weight = 200
#    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
