baseURL = "https://jordiburgos.com/"
languageCode = "en-us"
title = "Jordi Burgos"

theme = "hyde"

[permalinks]
  posts = "/posts/:year/:title/"

# hyde config

[Menus]
  main = [
      {Name = "Posts", URL = "/posts/", weight = 1},
      {Name = "Github", URL = "https://github.com/jmaister"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/jordiburgos/"},
      {Name = "Twitter", URL = "https://twitter.com/jordimaister"}
  ]

[params]
  description = "Personal blog"

  themeColor = "theme-base-08"

googleAnalytics = "UA-45872762-1"
